# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PyTorch App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PyTorch App

  target 'PyTorch AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PyTorch AppUITests' do
    # Pods for testing
  end

end
